---
- hosts: all

- name: Import dynamic variables 
  import_playbook: ../static-assignments/common.yml   
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

- name: import database file
  import_playbook: ../static-assignments/database.yml

- name: Delete wireshark installation
  import_playbook: ../static-assignments/common-del.yml


- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
  